/**
 * Web Push (RFC 8291 `aes128gcm` + RFC 8292 VAPID) for Cloudflare Workers.
 *
 * Why this file exists: push notifications are the only way to reach a
 * user whose Cerebrum tab is closed. The in-app 15s inbox poll
 * (src/inbox.jsx) and cbNotify only fire while a tab is open; a closed
 * tab gets nothing until the next visit. The Push API + a service worker
 * (public/sw.js) closes that gap: the server POSTs an encrypted payload
 * to the browser vendor's push service, which wakes the service worker
 * even with no tab open.
 *
 * Constraints that shaped the implementation:
 *
 * - workerd has no `node:crypto` (nodejs_compat is not enabled), so
 *   everything here is WebCrypto (`crypto.subtle`) plus a small pure-JS
 *   P-256 scalar multiplication. The `web-push` npm package is Node-only
 *   and cannot run on this backend.
 * - A VAPID private key in the conventional format is just the 32-byte
 *   scalar `d` — but WebCrypto refuses to import an EC private JWK with
 *   only `d` (it demands x and y too). `vapidPublicFromPrivate()`
 *   recomputes the public point from `d` with plain BigInt arithmetic,
 *   so keys generated by `npx web-push generate-vapid-keys` work as-is.
 * - The server NEVER sees message content for E2EE threads: the payload
 *   builder emits "New message" there. Plaintext threads get a sender
 *   name + short preview, matching what the in-app notification shows.
 *
 * Environment:
 *   VAPID_PUBLIC_KEY  — base64url uncompressed P-256 point (committed in
 *                       wrangler.toml [vars]; served to clients via the
 *                       `push-config` action so there is one source of
 *                       truth). Needed for the Crypto-Key/VAPID headers
 *                       and for PushManager.subscribe() in the browser.
 *   VAPID_PRIVATE_KEY — base64url 32-byte scalar. SECRET. Set in
 *                       Cloudflare Pages → Settings → Variables and
 *                       Secrets, and in .dev.vars locally. Never committed.
 *   VAPID_SUBJECT     — optional contact URI for the VAPID JWT `sub`
 *                       claim (e.g. mailto:ops@askcerebrum.org).
 */

const TE = new TextEncoder();

/* ── base64url ─────────────────────────────────────────────────────── */

export function b64uEncode(bytes) {
  const u8 = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
  let bin = "";
  for (let i = 0; i < u8.length; i++) bin += String.fromCharCode(u8[i]);
  const b64 = typeof btoa === "function"
    ? btoa(bin)
    : Buffer.from(bin, "binary").toString("base64");
  return b64.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

export function b64uDecode(str) {
  if (typeof str !== "string" || !/^[A-Za-z0-9\-_]+$/.test(str)) {
    throw new Error("bad base64url");
  }
  let b64 = str.replace(/-/g, "+").replace(/_/g, "/");
  while (b64.length % 4) b64 += "=";
  if (typeof atob === "function") {
    const bin = atob(b64);
    const u8 = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) u8[i] = bin.charCodeAt(i);
    return u8;
  }
  return new Uint8Array(Buffer.from(b64, "base64"));
}

/* ── P-256 scalar multiplication (pure JS, BigInt) ───────────────────
 * secp256r1 parameters. Only used to recover the public point from a
 * d-only VAPID private key — see the module comment. Double-and-add is
 * fine here: it runs once per push send at most (and the result should
 * be cached by callers that send in a loop). */

const P256 = {
  p: 0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFn,
  a: 0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFCn,
  b: 0x5AC635D8AA3A93E7B3EBBD557769886BC651D06B0CC53B0F63BCE3C3E27D2604Bn,
  gx: 0x6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296n,
  gy: 0x4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5n,
};

function modInv(x, p) {
  // Fermat: p is prime.
  let r = 1n, e = p - 2n, b = ((x % p) + p) % p;
  while (e > 0n) { if (e & 1n) r = (r * b) % p; b = (b * b) % p; e >>= 1n; }
  return r;
}

function pointAdd(P, Q) {
  const { p, a } = P256;
  if (!P) return Q;
  if (!Q) return P;
  if (P.x === Q.x && (P.y + Q.y) % p === 0n) return null; // P + (-P) = ∞
  let lam;
  if (P.x === Q.x && P.y === Q.y) {
    lam = ((3n * P.x * P.x + a) * modInv(2n * P.y, p)) % p;
  } else {
    lam = ((Q.y - P.y) * modInv(Q.x - P.x, p)) % p;
  }
  const rx = (lam * lam - P.x - Q.x) % p;
  const ry = (lam * (P.x - rx) - P.y) % p;
  return { x: (rx + p) % p, y: (ry + p) % p };
}

function scalarMult(k, P) {
  let R = null; // point at infinity
  let Q = P;
  let n = k;
  while (n > 0n) {
    if (n & 1n) R = pointAdd(R, Q);
    Q = pointAdd(Q, Q);
    n >>= 1n;
  }
  return R;
}

function bigToBytes(n, len) {
  let h = n.toString(16).padStart(len * 2, "0");
  const u8 = new Uint8Array(len);
  for (let i = 0; i < len; i++) u8[i] = parseInt(h.slice(i * 2, i * 2 + 2), 16);
  return u8;
}

function bytesToBig(u8) {
  let n = 0n;
  for (const b of u8) n = (n << 8n) | BigInt(b);
  return n;
}

/**
 * Recover the 65-byte uncompressed P-256 public key (0x04 || x || y)
 * from a 32-byte private scalar. Throws on an out-of-range scalar.
 */
export function vapidPublicFromPrivate(privBytes) {
  const d = bytesToBig(privBytes);
  const n = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551n;
  if (d <= 0n || d >= n) throw new Error("private scalar out of range");
  const P = scalarMult(d, { x: P256.gx, y: P256.gy });
  if (!P) throw new Error("point multiplication failed");
  const out = new Uint8Array(65);
  out[0] = 0x04;
  out.set(bigToBytes(P.x, 32), 1);
  out.set(bigToBytes(P.y, 32), 33);
  return out;
}

/* ── VAPID (RFC 8292) ──────────────────────────────────────────────── */

async function sha256(u8) {
  return new Uint8Array(await crypto.subtle.digest("SHA-256", u8));
}

async function hkdfExtract(salt, ikm) {
  const key = await crypto.subtle.importKey("raw", ikm, "HKDF", false, ["deriveBits"]);
  return new Uint8Array(await crypto.subtle.deriveBits(
    { name: "HKDF", hash: "SHA-256", salt, info: new Uint8Array(0) }, key, 256));
}

async function hkdfExpand(prk, info, len) {
  const key = await crypto.subtle.importKey("raw", prk, "HKDF", false, ["deriveBits"]);
  return new Uint8Array(await crypto.subtle.deriveBits(
    { name: "HKDF", hash: "SHA-256", salt: new Uint8Array(0), info }, key, len * 8));
}

/**
 * Build the Authorization / Crypto-Key headers for a push endpoint.
 * `aud` is the endpoint's origin (scheme + host), per RFC 8292 §2.
 * Returns { authorization, cryptoKey }.
 */
export async function vapidHeaders(endpoint, publicB64u, privateB64u, subject) {
  const aud = new URL(endpoint).origin;
  const header = b64uEncode(TE.encode(JSON.stringify({ typ: "JWT", alg: "ES256" })));
  const now = Math.floor(Date.now() / 1000);
  const claims = b64uEncode(TE.encode(JSON.stringify({
    aud, exp: now + 12 * 3600, sub: subject || "mailto:ops@askcerebrum.org",
  })));
  const unsigned = `${header}.${claims}`;
  // Rebuild the signing key from the d-only private scalar (see module
  // comment): derive x,y, then import the full JWK for ECDSA.
  const privBytes = b64uDecode(privateB64u);
  if (privBytes.length !== 32) throw new Error("VAPID private key must be 32 bytes");
  const pubRaw = vapidPublicFromPrivate(privBytes);
  const signingKey = await crypto.subtle.importKey("jwk", {
    kty: "EC", crv: "P-256",
    x: b64uEncode(pubRaw.slice(1, 33)),
    y: b64uEncode(pubRaw.slice(33, 65)),
    d: privateB64u,
  }, { name: "ECDSA", namedCurve: "P-256" }, false, ["sign"]);
  const sig = new Uint8Array(await crypto.subtle.sign(
    { name: "ECDSA", hash: "SHA-256" }, signingKey, TE.encode(unsigned)));
  const jwt = `${unsigned}.${b64uEncode(sig)}`;
  return {
    authorization: `vapid t=${jwt}, k=${publicB64u}`,
    // Older (draft-02) form still honored by FCM/autopush; harmless to
    // send alongside the RFC 8292 form.
    cryptoKey: `p256ecdsa=${publicB64u}`,
  };
}

/* ── Payload encryption (RFC 8291, aes128gcm) ───────────────────────── */

function concat(...parts) {
  const total = parts.reduce((n, p) => n + p.length, 0);
  const out = new Uint8Array(total);
  let o = 0;
  for (const p of parts) { out.set(p, o); o += p.length; }
  return out;
}

/**
 * Encrypt `plaintext` (Uint8Array) for a push subscription.
 * `subscription` = { p256dh: base64url, auth: base64url }.
 * Returns the full request body: salt || rs || idlen || as_public ||
 * ciphertext, with Content-Encoding: aes128gcm.
 */
export async function encryptPushPayload(subscription, plaintext) {
  const uaPublic = b64uDecode(subscription.p256dh);
  if (uaPublic.length !== 65 || uaPublic[0] !== 0x04) {
    throw new Error("subscription p256dh must be a 65-byte uncompressed point");
  }
  const authSecret = b64uDecode(subscription.auth);
  if (authSecret.length !== 16) throw new Error("subscription auth must be 16 bytes");

  const salt = crypto.getRandomValues(new Uint8Array(16));
  // Ephemeral sender key.
  const asKeys = await crypto.subtle.generateKey(
    { name: "ECDH", namedCurve: "P-256" }, true, ["deriveBits"]);
  const asPublic = new Uint8Array(await crypto.subtle.exportKey("raw", asKeys.publicKey));
  const uaKey = await crypto.subtle.importKey(
    "raw", uaPublic, { name: "ECDH", namedCurve: "P-256" }, false, []);
  const ecdhSecret = new Uint8Array(await crypto.subtle.deriveBits(
    { name: "ECDH", public: uaKey }, asKeys.privateKey, 256));

  const keyInfo = concat(TE.encode("WebPush: info"), new Uint8Array([0]), uaPublic, asPublic);
  const ikm = await hkdfExtract(authSecret, concat(ecdhSecret, keyInfo));
  const cek = await hkdfExpand(ikm, concat(TE.encode("Content-Encoding: aes128gcm"), new Uint8Array([0])), 16);
  const nonce = await hkdfExpand(ikm, concat(TE.encode("Content-Encoding: nonce"), new Uint8Array([0])), 12);

  // Pad: message || 0x02 delimiter. No extra padding — valid per §2 and
  // keeps the push small.
  const padded = concat(plaintext, new Uint8Array([0x02]));
  const aesKey = await crypto.subtle.importKey("raw", cek, { name: "AES-GCM" }, false, ["encrypt"]);
  const ciphertext = new Uint8Array(await crypto.subtle.encrypt(
    { name: "AES-GCM", iv: nonce }, aesKey, padded));

  // Body: salt(16) || rs(uint32be 4096) || idlen(1) || as_public(65) || ct.
  const header = new Uint8Array(16 + 4 + 1 + 65);
  header.set(salt, 0);
  new DataView(header.buffer).setUint32(16, 4096, false);
  header[20] = 65;
  header.set(asPublic, 21);
  return concat(header, ciphertext);
}

/* ── Sending ───────────────────────────────────────────────────────── */

/**
 * Validate a client-supplied push subscription. Returns the normalized
 * { endpoint, p256dh, auth } or throws with a human-safe reason.
 */
export function validatePushSubscription(sub) {
  if (!sub || typeof sub !== "object") throw new Error("subscription must be an object");
  const { endpoint, keys } = sub;
  if (typeof endpoint !== "string" || endpoint.length > 2000) throw new Error("bad endpoint");
  let url;
  try { url = new URL(endpoint); } catch { throw new Error("bad endpoint"); }
  // Push endpoints are always https. Accepting http would leak the
  // encrypted payload (and the VAPID JWT) to a network attacker.
  if (url.protocol !== "https:") throw new Error("endpoint must be https");
  if (!keys || typeof keys !== "object") throw new Error("missing keys");
  const p256dh = b64uDecode(String(keys.p256dh || ""));
  if (p256dh.length !== 65 || p256dh[0] !== 0x04) throw new Error("bad p256dh key");
  const auth = b64uDecode(String(keys.auth || ""));
  if (auth.length !== 16) throw new Error("bad auth secret");
  return { endpoint: url.toString(), p256dh: String(keys.p256dh), auth: String(keys.auth) };
}

/**
 * POST an encrypted push message to one subscription.
 * Returns { ok, status, gone } — `gone` is true on 404/410, meaning the
 * subscription is dead and should be deleted.
 */
export async function sendPushMessage(env, subscription, payloadBytes, opts = {}) {
  const publicKey = (env.VAPID_PUBLIC_KEY || "").trim();
  const privateKey = (env.VAPID_PRIVATE_KEY || "").trim();
  if (!publicKey || !privateKey) {
    return { ok: false, status: 0, gone: false, error: "vapid_not_configured" };
  }
  const body = await encryptPushPayload(subscription, payloadBytes);
  const { authorization, cryptoKey } = await vapidHeaders(
    subscription.endpoint, publicKey, privateKey, (env.VAPID_SUBJECT || "").trim() || undefined);
  const res = await fetch(subscription.endpoint, {
    method: "POST",
    headers: {
      "TTL": String(opts.ttl || 86400),
      "Content-Type": "application/octet-stream",
      "Content-Encoding": "aes128gcm",
      "Authorization": authorization,
      "Crypto-Key": cryptoKey,
      "Urgency": opts.urgency || "normal",
    },
    body,
  });
  return { ok: res.ok, status: res.status, gone: res.status === 404 || res.status === 410 };
}

/**
 * Build the push payload for a new inbox message. E2EE threads get no
 * content at all — the server can't read it anyway, and echoing
 * ciphertext into a push vendor's logs would be worse than useless.
 */
export function buildMessagePushPayload({ threadId, title, body, encrypted }) {
  const payload = {
    kind: "message",
    threadId: String(threadId || ""),
    title: String(title || "Cerebrum"),
    body: encrypted ? "New message" : String(body || "New message"),
    url: "/?inbox-thread=" + encodeURIComponent(String(threadId || "")),
  };
  return TE.encode(JSON.stringify(payload));
}

/* ── Subscription storage (D1) ───────────────────────────────────────
 * Pure against the D1 binding — unit-testable with a fake. Table:
 *   push_subscriptions(user_id TEXT, endpoint TEXT, p256dh TEXT,
 *     auth TEXT, created_at INTEGER, PRIMARY KEY(user_id, endpoint)) */

export const PUSH_SUBSCRIPTIONS_DDL = `
CREATE TABLE IF NOT EXISTS push_subscriptions (
  user_id    TEXT NOT NULL,
  endpoint   TEXT NOT NULL,
  p256dh     TEXT NOT NULL,
  auth       TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  PRIMARY KEY (user_id, endpoint)
);
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user ON push_subscriptions(user_id);`.trim();

export async function storePushSubscription(db, userId, sub) {
  const now = Date.now();
  await db.prepare(
    `INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth, created_at)
     VALUES (?, ?, ?, ?, ?)
     ON CONFLICT(user_id, endpoint) DO UPDATE SET
       p256dh = excluded.p256dh, auth = excluded.auth, created_at = excluded.created_at`
  ).bind(userId, sub.endpoint, sub.p256dh, sub.auth, now).run();
}

export async function removePushSubscription(db, userId, endpoint) {
  if (endpoint) {
    await db.prepare(
      "DELETE FROM push_subscriptions WHERE user_id = ? AND endpoint = ?"
    ).bind(userId, endpoint).run();
  } else {
    await db.prepare(
      "DELETE FROM push_subscriptions WHERE user_id = ?"
    ).bind(userId).run();
  }
}

export async function getPushSubscriptionsForUsers(db, userIds) {
  if (!userIds.length) return [];
  const placeholders = userIds.map(() => "?").join(",");
  const rows = await db.prepare(
    `SELECT user_id, endpoint, p256dh, auth FROM push_subscriptions WHERE user_id IN (${placeholders})`
  ).bind(...userIds).all();
  return rows.results || [];
}
