/**
 * The About / Privacy / Terms / Disclosures / Contact content.
 *
 * Extracted from the component that used to hold it inline for one reason:
 * these five pages were reachable ONLY by running React. A crawler, a
 * compliance scanner, an app-store reviewer or anyone with JavaScript
 * disabled fetching https://askcerebrum.org/privacy received the generic
 * homepage shell — title, description and canonical all pointing at "/" —
 * and never saw a word of the policy. A privacy policy nobody can read
 * without executing your JavaScript is not published.
 *
 * scripts/prerender.mjs imports this at build time and writes real HTML for
 * each route. The React InfoPage imports the same object, so the static
 * document and the in-app view cannot drift apart.
 */

/* Version stamp for the legal documents. Kept here, beside the text it
 * describes, so the version and the content change together. */
export const LEGAL_VERSION = "2026-09-15";
export const LEGAL_UPDATED = "15 September 2026";

export const PAGES = {
    about: { eyebrow: "About", title: "A research instrument, not a chatbot", lede: "A research instrument that searches real scholarly databases and gives you answers you can trace to the source.", blocks: [ { h: "What it does", p: "You ask a scientific question. Cerebrum queries a group of open scholarly databases in parallel, scores what comes back for genuine relevance, and writes a summary constrained by what those papers actually say. Every citation is a real DOI you can open and check." }, { h: "The databases", list: ["Europe PMC: 43M articles", "PubMed: 36M articles", "OpenAlex: 250M works", "Semantic Scholar: 220M papers", "Crossref: 150M works", "arXiv, bioRxiv: preprints", "DOAJ, PLOS, Zenodo: open access", "CORE, BASE, PMC full-text, OpenAIRE: additional aggregator/repository coverage"] }, { h: "The principle", p: "If no papers are retrieved for a question, Cerebrum says so plainly rather than inventing sources. A confident guess dressed up as science is worse than an honest 'nothing found.' That constraint is enforced mechanically, not just requested politely." }, { h: "What it is not", list: ["Not a substitute for reading the papers. Every summary is AI-generated, so verify anything you'll rely on.", "Not a medical, legal, or financial advisor.", "Not tracked or monetized, no ads, no selling data, and an account (optional, only for syncing your saved articles and history) is never required to use it."] } ],
      /* Frequently asked questions. Rendered as a visible section on /about
       * (both the prerendered document and the in-app InfoPage read this
       * same array) and emitted as FAQPage structured data in the
       * prerendered head, so search engines and AI answer products can lift
       * crisp, attributable answers. Keep each answer to one to three
       * sentences, factual, and self-contained: these sentences are written
       * to be quoted. */
      faq: [
        { q: "What is Cerebrum?", a: "Cerebrum is a free scientific literature search engine. You ask a research question and it returns an answer assembled from 15 open scholarly databases, with every claim linked to a real paper you can open." },
        { q: "Is Cerebrum free?", a: "Yes. Cerebrum is free to use, with no advertising, no tracking pixels, no third-party analytics, and no sale of personal information." },
        { q: "Which databases does Cerebrum search?", a: "Fifteen open scholarly sources: PubMed, Europe PMC, OpenAlex, Semantic Scholar, Crossref, arXiv, bioRxiv and medRxiv, DOAJ, PLOS, Zenodo, CORE, BASE, PubMed Central full-text, and OpenAIRE." },
        { q: "How is Cerebrum different from Google Scholar?", a: "Google Scholar returns a list of papers to sift through yourself. Cerebrum queries its databases in parallel, scores the results for genuine relevance, and writes a summary constrained by what the retrieved papers actually say, with every citation linked to a real DOI. And if nothing relevant is found, it says so instead of inventing sources." },
        { q: "Do I need an account to use Cerebrum?", a: "No. Guest mode works fully without an account, and your work stays in your own browser. An account is optional and exists only so your saved articles and history follow you to another device." },
        { q: "Is my search private?", a: "Cerebrum runs no advertising, no tracking pixels, and no third-party analytics, and it does not sell personal information. Your question is sent to Cerebrum's server to run the search, and onward to the scholarly databases and the language-model provider that generates the summary." },
        { q: "Can I trust Cerebrum's answers?", a: "Every answer is an AI-generated summary of retrieved records, so verify anything you rely on against the cited primary sources. The model can misread abstracts, conflate findings, or misattribute results. Cerebrum is a starting point for a literature search, not a substitute for reading the papers, and never a source of medical, legal, or financial advice." },
        { q: "Does Cerebrum include preprints?", a: "Yes, deliberately: important work often appears on preprint servers first. Preprints from arXiv, bioRxiv, and medRxiv are labeled as such, because they have not been through peer review and should be weighted accordingly." },
      ] },
    privacy: { eyebrow: "Privacy", title: "Privacy Policy", lede: "No advertising. No tracking pixels. No third-party analytics. No sale of personal information. This page explains exactly what is collected, why, who touches it, and how to get rid of it.", updated: `Version ${LEGAL_VERSION} · Last updated ${LEGAL_UPDATED}`, blocks: [
      { h: "1. The short version", list: [
        "Guest mode needs no account and stores your work only in your own browser.",
        "Your search question is sent to our server to run the search. It has to be, that is the search.",
        "We run no advertising, no tracking pixels, no third-party analytics, and no ad networks, with or without an account.",
        "We do not sell or share personal information, and we never have.",
        "An account exists for one reason: so your saved work follows you to another device.",
        "You can delete your account and its data from Settings, permanently, without emailing anyone."
      ] },
      { h: "2. Who is responsible for your data", p: "The operator of askcerebrum.org is the data controller for the information described here. For any privacy question, request, or complaint, contact dusty@askcerebrum.org. If you are in the EEA or UK you also have the right to complain to your local supervisory authority." },
      { h: "3. What we collect in guest mode", p: "Guest mode is the default and needs no account. Your saved articles, collections, conversation history, and preferences are written to your own browser's local storage and cookies. They are not sent to us, they are not readable by us, and clearing your browser data deletes them permanently, including from us, because we never had them." },
      { h: "4. What happens when you search", list: [
        "Your question is transmitted to our server so the search can run, and is sent onward to the scholarly databases and to the language-model provider that generates the summary.",
        "Answers may be cached, keyed by the question text, so a repeated question is faster and costs the upstream providers less.",
        "We keep short-lived request logs (timestamp, coarse endpoint, and an IP-derived value used for rate limiting) to keep the service up and to stop abuse.",
        "We do not build a profile of you from your questions, and we do not link guest-mode queries to an identity.",
        "Please do not put personal health information, identifying details about other people, or confidential material into a query. It leaves your device and reaches third-party providers."
      ] },
      { h: "5. What an account adds", p: "If you create an account we store your email address, a password hash if you set a password, and the content you explicitly choose to sync: saved sources, collections, conversation history, profile fields you fill in, watched topics, and, if you use the social features, your follows, direct messages, message attachments, and call signalling records, and your Pro subscription status. That is the whole list. Signing in changes nothing about how a search itself works." },
      { h: "6. Direct messages and calls", p: "Direct messages and their attachments are stored on our servers so they can be delivered to the recipient and shown to both of you later. They are not end-to-end encrypted: treat them as you would email, not as a confidential channel. Calls are established peer-to-peer where the network allows and are relayed through a public TURN service when it does not; we store only the short-lived signalling records needed to connect a call, and we do not record call audio or video. Conduct reports you file are stored so they can be reviewed." },
      { h: "7. Cookies and local storage", p: "We use no advertising or analytics cookies. Everything we set is functional: either your own preferences or your login session:", list: [
        "cb_sess. Your signed-in session token. Set only if you sign in.",
        "cb_pal, cb_accent, cb_ca, cb_density, cb_fs, cb_ls, cb_hc, cb_rt, cb_df, cb_fh: appearance and accessibility preferences.",
        "cb_len, cb_cite, cb_tw, cb_fc: response and citation preferences.",
        "cb_muted, cb_snd, cb_ap: sound, ambience, and read-aloud preferences.",
        "cb_anim2, cb_animS: motion preferences.",
        "cb_notify, which desktop notifications you have allowed.",
        "cb_legal. The version of these policies you have accepted, and when.",
        "Local storage: cb_saved, cb_history, cb_collections, cb_streak, cb_profile, cb_watch_notified, cb_tour_done, and any optional third-party API key you choose to paste into Settings.",
        "Because none of these are tracking cookies, there is no consent banner to dismiss, but you can clear them at any time from your browser, or reset preferences from Settings."
      ] },
      { h: "8. Legal bases for processing (EEA/UK)", list: [
        "Performance of a contract: running searches, delivering messages, and keeping your account working.",
        "Legitimate interests: security, abuse prevention, rate limiting, and keeping the service available, balanced against your rights.",
        "Consent, optional extras such as desktop notifications and any third-party API key you supply. You can withdraw consent at any time in Settings.",
        "Legal obligation: where we must retain or disclose something by law."
      ] },
      { h: "9. Who else processes your data", p: "We keep the list of third parties as short as the service allows. Each of them acts as a processor or independent controller for the narrow purpose described:", list: [
        "Cloudflare: hosting, edge delivery, database, and the AI inference that generates answers.",
        "Stripe: payment processing for Pro subscriptions. Card and payment details go directly to Stripe; we never see or store your card number. Stripe receives your email address and subscription information to operate billing.",
        "Language-model providers reached through our server to generate summaries. Your question text reaches them; your identity does not.",
        "Scholarly data providers: Europe PMC, PubMed/NCBI, OpenAlex, Crossref, Semantic Scholar, arXiv, bioRxiv/medRxiv, DOAJ, PLOS, Zenodo, CORE, BASE, OpenAIRE. Each receives the search terms needed to answer your query.",
        "A public STUN/TURN relay, used only to establish calls when a direct connection is impossible.",
        "Optional and only if you enable them: ElevenLabs for premium narration and Zotero for reference export, using a key you supply and that stays in your browser.",
        "We do not sell, rent, or share personal information with advertisers or data brokers. We have no advertising relationships of any kind."
      ] },
      { h: "10. International transfers", p: "The service runs on a global edge network, so processing may occur outside your country, including in the United States. Where data leaves the EEA or UK we rely on appropriate safeguards, such as standard contractual clauses entered into by our providers." },
      { h: "11. How long we keep things", list: [
        "Account data: until you delete your account, which removes it.",
        "Saved sources, collections, history, watched topics: until you delete them or your account.",
        "Direct messages, until you or the other participant deletes the conversation, or until the account is deleted.",
        "Call signalling records: minutes; they exist only to connect a call.",
        "Answer cache entries: a bounded period, keyed by question text rather than by user.",
        "Rate-limit and security logs: a short rolling window.",
        "Guest-mode data, for as long as you keep it in your own browser. We never receive it."
      ] },
      { h: "12. Your rights", p: "Depending on where you live you may have the right to access, correct, delete, restrict, or object to the processing of your personal information, and to receive it in a portable format. Cerebrum is built so you can exercise most of these yourself and immediately: Settings gives you a full JSON export of your workspace, per-item deletion, and permanent account deletion. For anything you cannot do in the app, email dusty@askcerebrum.org and we will respond within the period your law requires.", list: [
        "EEA/UK (GDPR): access, rectification, erasure, restriction, objection, portability, withdrawal of consent, and complaint to a supervisory authority.",
        "California (CCPA/CPRA): know, delete, correct, and opt out of sale or sharing. We do not sell or share personal information, so there is nothing to opt out of, and we will not discriminate against you for exercising any right.",
        "We honour Global Privacy Control and Do Not Track signals by default, because we run no tracking to disable in the first place."
      ] },
      { h: "13. Security", list: [
        "Passwords are hashed with PBKDF2-SHA256 at 100,000 iterations with a per-user salt. We never store or transmit them in plaintext and cannot recover them.",
        "Session tokens are opaque, random, expiring, and stored as HttpOnly, Secure, SameSite cookies, so page scripts cannot read them.",
        "All traffic is served over HTTPS, and a strict Content Security Policy limits what the page may load or connect to.",
        "Every account-scoped database query is scoped to your user id, not only to a row id, so one account cannot read another's rows by guessing.",
        "No system is perfectly secure. If you find a vulnerability, please see the responsible-disclosure process on the Disclosures page."
      ] },
      { h: "14. Children", p: "The Service is not directed at children under 13, and we do not knowingly collect personal information from them. If you believe a child under 13 has given us personal information, email dusty@askcerebrum.org and we will delete it. In the EEA and UK the minimum age is 16 without parental consent." },
      { h: "15. Data breaches", p: "If a breach occurs that is likely to affect your rights, we will notify affected users and the relevant supervisory authority within the timeframes our law requires, and we will tell you what happened, what data was involved, and what to do about it." },
      { h: "16. Changes to this policy", p: "We may update this policy. Material changes update the version identifier at the top of this page, and we will ask you to review and accept the new version before you continue using the Service. Prior versions are available on request." },
      { h: "17. Contact", email: "dusty@askcerebrum.org", p: "Privacy questions, data requests, and complaints." }
    ] },
    terms: { eyebrow: "Terms", title: "Terms of Service", lede: "These terms are a binding agreement between you and Cerebrum. Please read them: the sections on accuracy, professional advice, and liability affect your legal rights.", updated: `Version ${LEGAL_VERSION} · Last updated ${LEGAL_UPDATED}`, blocks: [
      { h: "1. Agreement to these terms", p: "By accessing or using Cerebrum (the \"Service\") at askcerebrum.org, you agree to be bound by these Terms of Service and by our Privacy Policy and Disclosures, which are incorporated here by reference. If you do not agree, do not use the Service. If you use the Service on behalf of an organization, you represent that you have authority to bind that organization, and \"you\" means that organization." },
      { h: "2. What Cerebrum is, and is not", p: "Cerebrum is a free research instrument. It queries public scholarly databases, retrieves records and abstracts, and uses a large language model to summarize what it retrieved, with citations back to the source. It is a starting point for a literature search and a tool for finding papers you should read yourself." },
      { h: "Cerebrum is NOT", list: [
        "A source of medical, legal, financial, psychological, veterinary, engineering, or safety advice.",
        "A substitute for reading the cited papers, or for a qualified professional.",
        "A diagnostic tool, a clinical decision support system, or a medical device.",
        "A publisher, peer reviewer, or verifier of the third-party research it indexes.",
        "A guaranteed-accurate, guaranteed-complete, or guaranteed-available service."
      ] },
      { h: "3. Eligibility", p: "You must be at least 13 years old to use the Service. If you are in the European Economic Area or the United Kingdom, you must be at least 16, or have the consent of a parent or guardian. The Service is not directed at children under 13 and we do not knowingly collect their personal information, see the Privacy Policy. If you are under the age of majority where you live, you may use the Service only with the involvement of a parent or guardian." },
      { h: "4. Accounts", p: "An account is optional; guest mode works fully without one. If you create one, you are responsible for the security of your account and for everything done through it. Provide accurate information, keep your credentials confidential, and tell us promptly at dusty@askcerebrum.org if you believe your account has been compromised. You may delete your account at any time from Settings, which permanently removes your account data from our servers." },
      { h: "5. Pro subscriptions, billing, and refunds", p: "The free tier of Cerebrum is free: no account, no payment, no catch. Cerebrum Pro is an optional paid subscription for users who want more.", list: [
        "Plans and pricing: Pro costs $20 per month or $144 per year, billed in advance in US dollars. Verified college students can get Pro for $7.99 per month for the first 12 months; after that the subscription renews at the standard monthly price unless cancelled. Applicable taxes may be added at checkout. The current prices and exactly what Pro includes are shown before you pay.",
        "Auto-renewal: your subscription renews automatically at the end of each billing period until you cancel. Cancel any time from your account's billing portal. Cancellation stops future charges, and your Pro access continues until the end of the period you already paid for.",
        "No partial-period refunds: apart from the money-back window below, we do not refund part of a month or year because you cancelled early or stopped using Pro.",
        "7-day money-back guarantee: if you email dusty@askcerebrum.org within 7 days of the first charge on a new subscription, we refund it in full, no questions asked. The same 7-day window applies to the first charge of an annual plan.",
        "Failed payments: if a renewal charge fails we retry, and Pro stays active during a short grace period. If payment ultimately cannot be collected, Pro access is suspended until you update your payment method.",
        "Refunds go back to the original payment method and typically arrive within 5 to 10 business days, depending on your bank.",
        "Lifetime Pro grants given directly by the founder are free, involve no payment, and are not affected by subscription changes or cancellations.",
        "Price changes: if Pro pricing changes we will notify you at least 30 days before your next renewal, and the new price applies only from that renewal. You can cancel before then if you prefer.",
        "If a charge looks wrong, email us first at dusty@askcerebrum.org before filing a chargeback. Most billing mistakes are fixed the same day."
      ] },
      { h: "6. Acceptable use", p: "You agree not to:", list: [
        "Disrupt, degrade, overload, or circumvent the Service, its rate limits, or its security controls.",
        "Systematically scrape, crawl, mirror, cache at scale, resell, or redistribute the Service's outputs, or use them to train a competing model.",
        "Use automated means to access the Service except as expressly permitted.",
        "Generate or distribute content intended to defraud, defame, harass, threaten, endanger, or discriminate against any person or group.",
        "Present Cerebrum's output as peer-reviewed research, as your own original scholarship, or as professional advice from a licensed practitioner.",
        "Use the Service to make decisions about a person's medical care, legal position, employment, credit, housing, or insurance.",
        "Attempt to re-identify individuals, extract personal data, or use the messaging or calling features to send unsolicited bulk messages.",
        "Upload, transmit, or link to malware, or to content you do not have the right to share.",
        "Violate the terms of any upstream scholarly database, publisher, or repository the Service links to.",
        "Reverse engineer, decompile, or attempt to derive the source of any non-public part of the Service, or probe it for vulnerabilities without following the disclosure process in our Disclosures page."
      ] },
      { h: "7. AI-generated content and accuracy", p: "Answers are generated by a large language model from records retrieved at query time. Language models can misread, over-generalize, conflate sources, misattribute findings, and state incorrect things fluently and confidently. Retrieval can miss relevant work or surface irrelevant work. Some indexed records are preprints that have not been peer reviewed. You are responsible for verifying anything you rely on against the cited primary sources. Cerebrum's accuracy indicators, confidence language, and fact-check pass are aids to judgment, not guarantees, and must not be read as certification that a statement is true." },
      { h: "8. No professional advice, and no reliance", p: "Nothing produced by the Service is professional advice of any kind, and no professional relationship is created by using it. Never disregard, delay, or override advice from a qualified professional because of something Cerebrum said. If you may be experiencing a medical emergency, contact your local emergency number or a licensed clinician immediately. Reliance on the Service is at your sole risk." },
      { h: "9. Third-party sources and content", p: "Cerebrum retrieves from, links to, and displays metadata and abstracts from independent third-party sources, including Europe PMC, PubMed/NCBI, OpenAlex, Crossref, Semantic Scholar, arXiv, bioRxiv and medRxiv, DOAJ, PLOS, Zenodo, CORE, BASE, OpenAIRE, and public feeds such as NASA APOD, and it may embed third-party video. Those materials belong to their authors, publishers, and providers. Cerebrum does not own, endorse, verify, or control them, is not affiliated with them, and is not responsible for their content, licensing, availability, or accuracy. Your use of any linked or embedded third-party material is governed by that third party's own terms and privacy policy. Where a source requires attribution, we display it; where a source's licence restricts reuse, that restriction travels with the content and binds you too." },
      { h: "10. Intellectual property", p: "The Service's software, interface, design, and branding are owned by Cerebrum and its licensors and are protected by intellectual property law. These terms grant you a limited, personal, revocable, non-exclusive, non-transferable licence to use the Service as intended, and nothing more. Cited papers, abstracts, figures, and metadata remain the property of their respective rights holders. As between you and Cerebrum, you may use the Service's generated summaries for your own research, teaching, and internal work, subject to the restrictions in section 5 and to the rights of the underlying sources, but generated text may reproduce or closely paraphrase source material, so you remain responsible for citation and for any onward publication." },
      { h: "11. Copyright complaints", p: "If you believe material accessible through the Service infringes your copyright, email dusty@askcerebrum.org with: identification of the work, identification of the material and where it appears, your contact details, a statement that you have a good-faith belief the use is unauthorized, a statement under penalty of perjury that your notice is accurate and that you are the owner or authorized to act, and your physical or electronic signature. We will investigate and remove or disable access to infringing material where appropriate, and we may terminate the accounts of repeat infringers." },
      { h: "12. Your content and communications", p: "The Service includes optional features that let you save sources, keep collections and history, publish a profile, send direct messages, share attachments, and place audio or video calls to other users. You retain ownership of what you create. You grant Cerebrum a limited licence to store, process, transmit, and display that content solely to operate the features you are using. You are responsible for what you send, and you must not use these features to harass, defraud, or distribute unlawful material. We may remove content and suspend accounts that breach these terms or that are reported to us and found to breach them. Calls are peer-to-peer where the network permits; we do not record calls." },
      { h: "13. Privacy", p: "Our handling of personal information is described in the Privacy Policy, which forms part of this agreement. In short: no advertising, no tracking pixels, no sale of personal information, and the minimum data needed to run the features you use." },
      { h: "14. Availability, changes, and termination", p: "The free tier of the Service is provided free of charge and with no availability commitment. Paid Pro subscriptions are governed additionally by section 5. We may change, suspend, limit, or discontinue any part of the Service, including individual features and rate limits, at any time and without notice, subject to section 5 for active paid subscriptions. We may suspend or terminate your access if you breach these terms, if we are required to by law, or if continuing would create risk for other users or for the Service. You may stop using the Service at any time and delete your account from Settings. Sections that by their nature should survive termination, including 7 through 12 and 15 through 20, survive it." },
      { h: "15. Disclaimer of warranties", p: "THE SERVICE, INCLUDING ALL CONTENT AND OUTPUT, IS PROVIDED \"AS IS\" AND \"AS AVAILABLE\", WITHOUT WARRANTIES OF ANY KIND, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WITHOUT LIMITATION IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, AND ANY WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE OF TRADE. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT ANY OUTPUT IS ACCURATE, COMPLETE, CURRENT, OR RELIABLE. Some jurisdictions do not allow the exclusion of implied warranties, so parts of this section may not apply to you." },
      { h: "16. Limitation of liability", p: "TO THE MAXIMUM EXTENT PERMITTED BY LAW, CEREBRUM AND ITS OPERATORS, CONTRIBUTORS, AND LICENSORS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, REVENUE, DATA, GOODWILL, RESEARCH TIME, OR BUSINESS OPPORTUNITY, ARISING OUT OF OR RELATING TO YOUR USE OF OR INABILITY TO USE THE SERVICE, INCLUDING ANY RELIANCE ON ITS OUTPUT, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICE WILL NOT EXCEED ONE HUNDRED US DOLLARS (US$100), OR THE AMOUNT YOU PAID US IN THE TWELVE MONTHS BEFORE THE CLAIM, WHICHEVER IS GREATER. Nothing in these terms excludes or limits liability that cannot lawfully be excluded or limited, including liability for death or personal injury caused by negligence, or for fraud. Some jurisdictions do not allow certain limitations, so parts of this section may not apply to you." },
      { h: "17. Indemnification", p: "You agree to indemnify and hold harmless Cerebrum and its operators from any claim, demand, loss, liability, or expense (including reasonable legal fees) arising out of your use of the Service, your content, your breach of these terms, or your violation of any law or third-party right." },
      { h: "18. Governing law and disputes", p: "These terms are governed by the laws of the State of Tennessee, United States, without regard to its conflict-of-law rules. You and we agree that the exclusive venue for any dispute arising out of or relating to these terms or the Service is the state or federal courts located in Knox County, Tennessee, and each of us consents to personal jurisdiction there. If you are a consumer resident in the European Economic Area or the United Kingdom, nothing here deprives you of the protection of the mandatory consumer-protection laws of your country of residence, or of your right to bring proceedings in your local courts. Before filing any claim, please email dusty@askcerebrum.org and give us thirty days to try to resolve it informally. Most things can be sorted out that way." },
      { h: "19. Changes to these terms", p: "We may update these terms. When we make a material change we will update the version identifier at the top of this page and ask you to review and accept the new version before continuing to use the Service. Continued use after a non-material update means you accept it. Prior versions are available on request." },
      { h: "20. General", p: "These terms, together with the Privacy Policy and the Disclosures page, are the entire agreement between you and us about the Service. If any provision is held unenforceable, the rest remains in effect and the unenforceable part is limited to the minimum extent necessary. Our failure to enforce a provision is not a waiver of it. You may not assign this agreement; we may assign it in connection with a merger, acquisition, or transfer of the Service." },
      { h: "21. Contact", email: "dusty@askcerebrum.org", p: "Questions about these terms, or about anything on this page." }
    ] },
    disclosures: { eyebrow: "Disclosures", title: "Disclosures", lede: "The things you should know about how Cerebrum works before you rely on it: stated plainly, in one place, rather than buried in the terms.", updated: `Version ${LEGAL_VERSION} · Last updated ${LEGAL_UPDATED}`, blocks: [
      { h: "AI-generated content", p: "Every answer on this site is written by a large language model, not by a person and not by the authors of the cited papers. The model summarizes records retrieved at the moment you asked. It can misread an abstract, merge two findings into one, attribute a result to the wrong study, or state something incorrect in completely fluent prose. Citations are inserted by the model and can point at the wrong source even when the sentence is right. Treat every answer as a lead to check, never as a finding to quote." },
      { h: "Not medical advice", p: "Cerebrum is not a doctor, a clinical decision support system, or a medical device, and nothing it produces is medical advice, diagnosis, or treatment. Do not use it to diagnose yourself or anyone else, to choose or change a treatment, to set a dose, or to decide whether to seek care. Always consult a qualified clinician. If you may be having a medical emergency, call your local emergency number now." },
      { h: "Not legal, financial, or safety advice", p: "Cerebrum does not give legal, financial, tax, engineering, chemical-safety, or biosafety advice, and no professional relationship is created by using it. Do not use its output to assess a legal position, make an investment, design a structure, or plan an experiment or procedure with safety implications, without a qualified professional." },
      { h: "Preprints are not peer-reviewed", p: "Cerebrum deliberately indexes preprint servers, bioRxiv, medRxiv, arXiv, and others reached through Europe PMC, because important work often appears there first. Preprints have not been through peer review. Cerebrum labels them, and you should weight them accordingly." },
      { h: "Coverage is incomplete", p: "Cerebrum queries fifteen sources. That is a lot, and it is still not all of the literature. Paywalled full texts, books, theses, non-English work, older material that was never digitized, and anything outside the indexed databases can be missed entirely. An absence of results in Cerebrum is not evidence that no research exists." },
      { h: "Accuracy indicators are aids, not certificates", p: "Source-alignment scores, confidence language, evidence-tier filters, and the optional fact-check pass are heuristics designed to help you judge an answer faster. They are computed automatically, they can be wrong in both directions, and none of them is a certification that a statement is true." },
      { h: "No affiliation or endorsement", p: "Cerebrum is independent. It is not affiliated with, endorsed by, sponsored by, or acting on behalf of any publisher, database, university, journal, funder, or the authors of any cited work. Names, logos, and trademarks belong to their owners and appear here for identification and attribution only." },
      { h: "Data providers and attribution", p: "Cerebrum is built on public scholarly infrastructure and is grateful for it. Records come from Europe PMC, PubMed and NCBI E-utilities, OpenAlex, Crossref, Semantic Scholar, arXiv, bioRxiv and medRxiv, DOAJ, PLOS, Zenodo, CORE, BASE, and OpenAIRE. Daily-science items may come from public feeds including NASA's Astronomy Picture of the Day. Each provider's content remains under its own licence and terms; where a licence requires attribution we display it, and where it restricts reuse that restriction applies to you as well." },
      { h: "Availability", p: "Cerebrum is free, provided as-is, and offered with no uptime commitment. Upstream databases go down, rate-limit us, or change their responses without notice, and features can be changed or withdrawn at any time. Do not build a workflow that cannot tolerate the service being unavailable." },
      { h: "Rate limits", p: "Requests are rate limited per account or per network address to keep the service usable for everyone and to stay within what the upstream providers allow. Hitting a limit is not an error in your query; wait and try again." },
      { h: "Messages and calls are not confidential", p: "Direct messages are stored on our servers so they can be delivered and are not end-to-end encrypted. Calls are peer-to-peer where the network allows and relayed otherwise; we do not record them, but we cannot promise the path is private. Do not use either for patient data, legal privilege, unpublished confidential results, or anything else that would harm you if disclosed." },
      { h: "Accessibility", p: "Cerebrum aims to meet WCAG 2.1 Level AA. The interface offers high-contrast mode, adjustable text size and line spacing, a dyslexia-friendly typeface, reduced transparency, visible focus indicators, full keyboard navigation, and honours your operating system's reduced-motion setting. If something is unusable for you, email dusty@askcerebrum.org and describe what you hit, accessibility reports are treated as bugs, not requests." },
      { h: "Responsible security disclosure", p: "If you find a vulnerability, email dusty@askcerebrum.org with enough detail to reproduce it, and please give us a reasonable chance to fix it before disclosing publicly. Do not access, modify, or delete other people's data, do not degrade the service for others, and do not run automated scanning that amounts to a denial-of-service. We will not pursue action against good-faith research that follows this process." },
      { h: "Reporting a bad answer", p: "Wrong species, invented citation, misattributed finding, an answer that reads as medical advice? Report it in the app or email dusty@askcerebrum.org with the exact question. Bad answers are the highest-priority bug class here." },
      { h: "Contact", email: "dusty@askcerebrum.org", p: "For anything on this page." }
    ] },
    contact: { eyebrow: "Contact", title: "Tell us what's broken or missing", lede: "Bug reports, feature requests, feedback, security issues: all welcome.", blocks: [ { h: "Email", email: "dusty@askcerebrum.org", p: "Include as much detail as you can. A bug report is far easier to act on with the exact query, your browser, and what you expected to see." }, { h: "Reporting a bad answer", p: "Found a wrong species, an invented citation, a misattributed finding? Email the exact question and a short description. This is how the system improves." }, { h: "Security", p: "Discovered a vulnerability? Email us with details and please hold off on public disclosure until we've had a chance to respond." }, { h: "Blocked at work?", p: "If your organization's web filter is blocking Cerebrum, email us. We can help get it recategorized correctly as Reference / Educational." } ] },
  };
